### ISSUE TITLE
`Fn::GetAtt` causes `Error converting: list index out of range`

### ISSUE THREAD

**Issue by PatMyron** [aperswal/CloudFormation_To_Terraform#8]
https://github.com/aperswal/CloudFormation_To_Terraform/blob/453012ab9aa3797142bbe2f6ef2d899cf91eeb13/cli_converter.py#L78-L79

**Reproduction template:**
```yaml
Resources:
  Resource:
    Type: AWS::SNS::Topic
  Resource5:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName:
        Fn::GetAtt: Resource.TopicName
```
**Can workaround with `!GetAtt` syntax:**
```yaml
Resources:
  Resource:
    Type: AWS::SNS::Topic
  Resource5:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName:
        !GetAtt Resource.TopicName
```
